parts = HW.Parts()
inventory = HW.Inventory()
#inventory.reset_database()
inventory.add_inv("bottled water", 24, "1.50")
# inventory.update_inv(1, 10, "1.99")
print(inventory.fetch_inv(1))
print(inventory.fetch_inv())
inventory.delete_inv(2)
print(inventory.fetch_inv())